### ISSUE TITLE
Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by janwo** [ruiquelhas/henning#10]
The following request made my server crash:

```
POST /api/account/delete-avatar HTTP/1.1
Host: localhost
Connection: keep-alive
Content-Length: 0
Pragma: no-cache
Cache-Control: no-cache
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbklkIjoiNWQyYzZlMmUtOWEzNi00Mjg4LTlhODEtODc3MmU1NTUyMDI3IiwidXNlcklkIjoiQnlwRW1DeldXIiwiaWF0IjoxNDk2MjI5NzA1fQ.0xvZgvoUPAcluVkAKM0sAOuBk24oOeJH4Kw4qFwG4bo
Origin: http://localhost
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
Content-Type: application/json
Accept: application/json, text/plain, */*
DNT: 1
Referer: http://localhost/settings/profile
Accept-Encoding: gzip, deflate, br
Accept-Language: de-DE,de;q=0.8,en-US;q=0.6,en;q=0.4
````
I get the following error: 

    /root/app/node_modules/thurston/lib/index.js:35
    const items = Object.keys(payload);
    TypeError: Cannot convert undefined or null to object   
    at Function.keys (<anonymous>)
    at Object.exports.validate [as validator] (/root/app/node_modules/thurston/lib/index.js:35:26)

I registered henning as described in the readme and use the following route config:

	{
		path: '/api/account/delete-avatar',
		method: 'POST',
		handler: AccountController.RouteHandlers.deleteAvatar,
		config: {
			auth: {
				scope: [
					UserRoles.user
				]
			}
		}
	},

**Comment by ruiquelhas** [comment]
Can you paste a dump (buffer or something) of the request body? Looking at the `Content-Type` I guess it's a JSON payload, which is weird because, in that case, it should be ignored.

**Comment by janwo** [comment]
How can I do that? IMO the text I pasted above, is the complete request.

**Comment by ruiquelhas** [comment]
I probably would not need that in any case. However, It's just not enough information. Your issue is that somewhere along the line, the `payload` object is not being correctly parsed by `hapi`, thus the error.

This does not look to be an issue with `henning`. Maybe you are using a different plugin or adding some extension method that leads to this behavior?

**Comment by janwo** [comment]
I am using the following plugins:
- inert
- vision
- henning
- good-squeeze
- good-console
- white-out
- rotating-file-stream
- bell
- hapi-auth-jwt2
- hapi-auth-basic
- auto-sni

There are no plugins, that might change the payload. Before using henning, I had no problems..

**Comment by ruiquelhas** [comment]
Ok, let's start over, I was a bit sleepy yesterday and did not even manage to look at your route. `henning` is meant to work only if the payload is processed as a `Stream`. So, in your example, since you don't specify that, `hapi` will just process it as a `Buffer` (which is the default behavior).

So, either you explicitly add the option like so: 

```js
{
    path: '/api/account/delete-avatar',
    method: 'POST',
    handler: AccountController.RouteHandlers.deleteAvatar,
    config: {
        auth: {
            scope: [
                UserRoles.user
            ]
        },
        payload: {
              output: 'stream',
              parse: true
        }
    }
}
``` 

Or you can always use [`houdin`](https://github.com/ruiquelhas/houdin) instead, which is basically the same, but validates `Buffer`-based payloads.

I'll probably add some checks to prevent this kind of exceptions and internally defer the validation to `houdin`. I'll have to assess that.

**Comment by ruiquelhas** [comment]
Check out [`copperfield`](https://github.com/ruiquelhas/copperfield) also, if you rely on `Buffer`-based request payloads across your app, you might as well use server-level validation (like `henning`) instead of route-level (`houdin`).

**Comment by janwo** [comment]
I think it does make sense that henning is ignoring any non-Stream-request. I need a stream validation at a single route only. Copperfield and houdin are using buffer-based payloads. I would really appreciate to have a plugin, that is checking all my stream-requests.

**Comment by ruiquelhas** [comment]
It works for routes that process and parse `Stream`-based payloads. The only way I could reproduce your issue is by using routes with a different kind of payload processing. And unless, you have a server-wide configuration, that specific route won't parse the payload as a `Stream`.

If you don't want to parse the payload, and use streaming, then what you need is [`burton`](http://github.com/ruiquelhas/burton/). Each module has a specific purpose. Maybe I'm in the wrong here, but I think I'm being clear about that in the `README`.

**Comment by janwo** [comment]
I like to have the single route parsed and outputted as a stream. All other routes, including the one I posted above, I want to skip the validation by henning. In the README you say "For every other route with a different configuration, the validation is skipped.". But in the dump I posted, the plugin crashed instead of skipping the validation for such configuration. Am I right?

**Comment by ruiquelhas** [comment]
You are right. However, the sentence is correct if and only if the payload is in fact a stream (which is not the case here, since the request payload `Content-Type` is `application/json`).

But, in practice what you really want is to have the content verified before doing any kind of validation, and that is feasible and makes sense. However, this isn't actually the module that needs to be patched for that, but [`thurston`](https://github.com/ruiquelhas/thurston) instead (yes, another one :laughing: ). I'll be patching it soon.

**Comment by janwo** [comment]
I think I got it 😄  Great, really appreciate you help! 👍

**Comment by ruiquelhas** [comment]
@janwo a fresh install should pull the latest version of `thurston`. It should solve your issue.

**Comment by janwo** [comment]
Works!! 🍾
